[package]
name = "memora"
description = "A build artifact cache for Git repositories"
version = "0.6.3"
authors = ["Andreas Kurth"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/accuminium/memora-rs"

[dependencies]
log = "0.4"
env_logger = "0.7"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = "2.33"
Inflector = "0.11"
file-lock = "2.1"
tuple-transpose = "0.1"
walkdir = "2.3"
derivative = "2.1"
serde-tuple-vec-map = "1.0"

[dev-dependencies]
tempdir = "0.3"
rand = "0.7"
maplit = "1.0"
file_diff = "1.0"
